filterSize = 3;
layers_ds = [
    imageInputLayer([32 32 1])
    convolution2dLayer(filterSize, 32, 'Padding', 'same')
    batchNormalizationLayer()
    reluLayer()
    maxPooling2dLayer(2,'Stride',2)
    convolution2dLayer(filterSize, 64, 'Padding', 'same')
    batchNormalizationLayer()
    reluLayer()
    maxPooling2dLayer(2,'Stride',2)
    convolution2dLayer(filterSize, 128, 'Padding', 'same')
    batchNormalizationLayer()
    reluLayer()
    maxPooling2dLayer(2,'Stride',2)
    convolution2dLayer(filterSize, 512, 'Padding', 'same')
    batchNormalizationLayer()
    reluLayer()
    upsamplingLayer("1")
    convolution2dLayer(filterSize, 128, 'Padding', 'same')
    batchNormalizationLayer()
    reluLayer()
    upsamplingLayer("2")
    convolution2dLayer(filterSize, 64, 'Padding', 'same')
    batchNormalizationLayer()
    reluLayer()
    upsamplingLayer("3")
    convolution2dLayer(filterSize, 32, 'Padding', 'same')
    batchNormalizationLayer()
    reluLayer()
    fullyConnectedLayer(32)
    regressionLayer
    ];

analyzeNetwork(layers_ds)